### ISSUE TITLE
Cannot find source / header files

### ISSUE THREAD

**Issue by hashim19** [TETYYS/ph-malhide#1]
Hi everyone, 
I am new to C/C++ programming. I am trying to run ph-malhide but I couldn't make it run. I do not know why it can't find these include files. What I did is:
1). I cloned the ph-malhide repository to my system and build it.
2.) But it is giving a lot errors that it cannot file these files.
Can you help me with this ? 

![processhacker2](https://cloud.githubusercontent.com/assets/13851084/25283038/d7c40812-26cb-11e7-8ca9-58ad283f0356.png)
![processhacker3](https://cloud.githubusercontent.com/assets/13851084/25283043/dc071d74-26cb-11e7-8576-cc5d21709db0.png)
![processhacker4](https://cloud.githubusercontent.com/assets/13851084/25283046/ddd7c28e-26cb-11e7-85ef-deee1d7b9a25.png)

**Comment by TETYYS** [comment]
You need to link it against ProcessHacker SDK

**Comment by hashim19** [comment]
Thanks for your reply. How can I link it with Process Hacker SDK ?

**Comment by hashim19** [comment]
Hi TETYYS, 
I have linked it with ProcessHacker sdk, but now it can't find ProcessHacker.lib file :/ . My sdk/lib/amd64 file is empty. what should I do ?

**Comment by TETYYS** [comment]
https://msdn.microsoft.com/en-us/library/ba1z7822.aspx

visual studio not finding ProcessHacker.lib is an indacation that you haven't linked it

**Comment by hashim19** [comment]
Thanks for your answer. I have done everything correctly and I successfully build the malhide. But it cannot load the malhide.dll file, saying that "Malhide.dll is not a valid win32 application"

**Comment by TETYYS** [comment]
Please find tech support somewhere else
